<?php

error_reporting(E_ALL|E_STRICT);
ini_set('display_errors', 1);

require '../vendor/autoload.php';

use CheckoutFinland\Poll;
use CheckoutFinland\Client;

$merchantId     = '375917';
$merchantSecret = 'SAIPPUAKAUPPIAS';

$stamp          = $_GET['STAMP']; // Stamp generated generated by webshop when creating the payment
$reference      = $_GET['REFERENCE']; // Refence number generated by webshop when creating the payment
$amount         = $_GET['AMOUNT']; // Amount in cents 1€ = 100

$poll = new Poll($merchantId, $merchantSecret);
$poll->setPaymentData($stamp, $reference, $amount);

$client = new Client();

$response = $client->poll($poll);

$response_xml = @simplexml_load_string($response);

if($response_xml) {
    // the status codes are listed in the api documentation of Checkout Finland
    switch ($response_xml->status) {
        case '2':
        case '5':
        case '6':
        case '8':
        case '9':
        case '10':
            // These are paid and we can ship the product
            $status_string = 'PAID';
            break;
        case '7':
        case '3':
        case '4':
            // Payment delayed or it is not known yet if the payment was completed
            $status_string = 'DELAYED';
            break;
        case '-1':
            $status_string = 'CANCELLED BY USER';
            break;
        case '-2':
        case '-3':
        case '-4':
        case '-10':
            // Cancelled by banks, Checkout Finland, time out e.g.
            $status_string = 'CANCELLED';
            break;
    }
}
?>
<!doctype html>

<html lang="en">
<head>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
    <!--[if lte IE 8]>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
    <!--<![endif]-->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Checkout Finland API example</title>
</head>

<body>
<div style="max-width:800px; margin:auto;">

    <h2>Poll response: <?php echo $status_string ?></h2>
    <p>
        <pre>
            <?php var_dump($response); ?>
        </pre>
    </p>
    <p><a href="index.html">Back to cart</a></p>
</div>
</body>
</html>
